version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "./api"
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "./front"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "sass-loader"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
